### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#574]
## TODO

- [x] merge: https://github.com/filebrowser/filebrowser/pull/575
- [x] finish docs: https://docs.filebrowser.xyz/
- [x] cleanup https://filebrowser.xyz/
- [x] check if docker image is OK

## After Release

- Caddy plugin release will be tied with next Caddy release which might take a while yet.

---

Hi everyone!

I was looking and the repo and noticed we have already more than 3800 stars and it makes me sad to know that the project is no longer active or even working on master...

In one/two months I'll have a break between uni semesters and I was thinking about giving this a clean up (and to the front-end too: it has a lot of old deps, and I'd like to move it to React).

With that revamp we'd remove the integration with Caddy, at least directly to the code. We could create a plugin that uses or even that downloads the binary. The integration with Caddy is more troublesome that it seems to be and it has always put some constrains on how we structure the code and the development.

In other news, the BoltDB DB is no longer active and I thought we could move to something more straightforward, with more background and with more tooling available such as SQLite.

The point would be to clean-up this repo and frontend, use go.mod and remove Caddy direct integrations (it can always be proxied by Caddy).

Also, with this rewrite, take in account the storage "issues" (#371).

I'm waiting to hear your feedback: @1138-4EB @Equim-chan

**Comment by hacdias** [comment]
- Also, make **filebrowser** mainly a binary and move **main.go** to the root of the repo.
- That would also block FileBrowser from being used as a middleware.
- Use github.com/spf13/afero as a FS layer instead of our own.
- Add an interactive first run experience through the command line to configure the stuff on the database and get rid of almost all flags.
	- This would still let users create instances through scripts, they would just need to provide the stuff in the same order as it is asked.
	- Also add commands to interact with the DB programatically.

**Comment by helloray** [comment]
Hi @hacdias 

I really like this project. Thanks for your great work. I really hope this project can be continued.
Because you are studying in the uni, I think you may not have so much time to rewrite the project. 
I don't know how much difference between VUE and React. If VUE works well, why spending so much time to rewrite it? Those frontend frameworks are almost changing everyday. The most popular framework can be die at any time. I suggest you keep working on features and bug fix. Do not rewrite it.

At the moment, the most important thing is to introduce vendor management for go. Without that,  the project can not be compiled if any go lib changing their APIs. Other contributors can gain benefits from it too.

They are still many features and improvements could be made for this project.
1. Folder upload(I can help to contribute it)
2. Scrollbar management(The scrollbar position should be recorded and restored when user go back to parent directory. After user change a file name, the scrollbar should also jump to that file related area. )
3. Preview enhancement(Current preview fetches the directory content everytime when user click prev/next button. This is extremely slow when the directory contains many files. Is it possible to cache the directory content?)
4.Thumbnails for Image/Video #128 (@vitaliy-kuzmich has made it.)
5.Floating music/video player #233, #421(@vitaliy-kuzmich has made it. Is it possible to make the music not stopped when operating filebrowser?)
6.Workaround for videos that can't stream in browser #465 
7.Fail to make archive with filenames that are too long #341

**Comment by hacdias** [comment]
Hey! When I said rewrite, it's not a complete rewrite from scratch. A lot of code will be reused. I started yesterday doing it (haven't pushed it yet) and the code is looking much better ... and smaller! There's a lot of stuff with the Go counterpart that can be improved. That's what I'm working on.  

Why rewrite the front end? Again, lot of code that ... Well... Doesn't need to be there. A lot of old dependencies and updating them will be an hassle. The ideia is to revamp it and then install greenkeeper to maintain the dependencies up to date. 

The codebase is not that big and could be smaller.  I can assure you I will have time for this 😄I don't have classes in January nor in the first half of February. Just two or three exams. I'll push the branch today

**Comment by helloray** [comment]
Hi @hacdias， If you did not mean complete rewrite it, please go ahead. I'm glad that you can come back on this project. Thanks a lot.

BTW, you mentioned remove the integration with Caddy, is it possible to add builtin https support? A single standalone binary is better than run two applications. If there is a lot of work to do, just ignore this request.

**Comment by hacdias** [comment]
@helloray :) sorry, what's wrong with https? Oh... adding the certificates? If that's it, yes, it can be added. Doesn't seem much hassle. I'll leave this issue opened. As soon as I'm finished with cleaning the old code, I'll take a look at some feature requests and implement them just to give FB a new look!

**Comment by laoshaw** [comment]
https with strong authentication mechanism to manage files via web browser is wonderful, really like this project. No I don't need php, nginx-reverse, mysql to do this, Go's one binary approach is the most elegant method.

and please replace the editor, monaco(?) or ACE definitely. Thanks!

**Comment by hacdias** [comment]
@laoshaw thanks! I'm adding that to the list of fixes (#575). The only feature that will certainly be removed is the direct integration with Caddy.

After this, I hope I can tackle more issues, but this will take a bit.

**Comment by Equim-chan** [comment]
> In other news, the BoltDB DB is no longer active and I thought we could move to something more straightforward, with more background and with more tooling available such as SQLite.

BoltDB is fine. It's not active because it's stable enough for now.

**Comment by hacdias** [comment]
@Equim-chan awesome then. That way I can reuse all the bolt db code 😄 I saw there's a fork with some fixes and such and even they recommend us to use it.

**Comment by hacdias** [comment]
@vitaliy-kuzmich I saw your fork and I thought it would be nice to ping you here. Look at what's done in #575.

**Comment by vitaliy-kuzmich** [comment]
@hacdias Thanks for ping.
Does it costs to do so much effort into DB management(example mysql workbench) from console ? Are there workbenches for bolt DB ? Maybe replace with SQLlite and use some UI ? Here it is for bolt: https://github.com/evnix/boltdbweb but I did not test it...

Just thinking to implement file sharing, and put it as separate menu item, next to files listing. Idea is to share files for all/selected users by using some access matrix in order to view it like usual files, but not only download. I am not sure, but I plan to use symbolic links, just create shared folder. In that folder each user would have own folder that named by user's name. After just symlink files to the user's folder, and anyone would see it, also deny/forbid modify access for anyone in that folder. Do you think would it works in windows ? I mean there is users, but why do you need to support windows then ? When filebrowser should works on server side, basically its a cloud. Fix me if I am wrong. Or do you want to make cloud and win support at the same time ?

**Comment by hacdias** [comment]
@vitaliy-kuzmich np. About the DB management: I'm sticking with bolt DB (it's just... simple and it doesn't have string limits nor anything else) and I've already implemented all the needed CLI commands.

Don't forget that there are lots of people that want to deploy "on demand" and I don't believe it should be their work to be generating a DB with the required structure.

If they use the commands from File Browser itself, they'll always make sure they have the correct DB structure. And lots of users have requested it already.

Having a shared folder would be interesting. Yes, symlinks works on Windows but I didn't quite understand what you want to do. I'm developing on Windows btw 😄

**Comment by vitaliy-kuzmich** [comment]
@hacdias I see now. Well, as I know, at this moment of time, it is not possible to view shared resource in the browser, but only download it. So I want to make 'view' feature of the shared resource, in addition to download. But it will be separated from shared link, because it is different, shared links are outside from DMZ(authenticated/authorized user), but shared folder inside. So then in case links access, you can use VPN for internal access, and bypass links URL through nginx(for example) directly to the public access. Matrix access that I mentioned, are about authorized users, so they could give/deny access from the specific user(groups later, maybe) to the specific folder, basically it is implemented in linux/win/osx, but I thinks it is better to have it in DB.

**Comment by hacdias** [comment]
@vitaliy-kuzmich gotcha. It's an interesting feature that may well be worth it to implement

**Comment by eine** [comment]
First off, wow! and thanks a lot for allocating time for this project. It is really exciting to see it moving forward!

You have been really busy this last week, so it is hard to grasp all the features that are being discussed here and modified in the related issues. I'll try to help by summarizing what I have understood so far, and providing my point of view on some of the issues.

---

I agree with:

> @helloray
> At the moment, the most important thing is to introduce vendor management for go. Without that, the project can not be compiled if any go lib changing their APIs. Other contributors can gain benefits from it too.

The most important and urgent issue is to add go mod support to either v1.10.0 or to the current master branch. That will allow users to use the *old* Filebrowser in a stable state. To do this, we need to decide:

- Stabilize v1.10.0 as v1.10.1 and jump directly to v2.0.0 in february.
- Stabilize the current master branch as v2.0.0 and jump to v3.0.0 in february.
- Stabilize the current master branch as v1.11.0 (although it might not be fully semver compilant) and jump to v2.0.0 in february.

---

About rewriting the frontend with React, I quite agree with:

> @helloray
> I don't know how much difference between VUE and React. If VUE works well, why spending so much time to rewrite it? Those frontend frameworks are almost changing everyday. The most popular framework can be die at any time. I suggest you keep working on features and bug fix. Do not rewrite it.

At the same time, @hacdias is young and this is a project he is doing in his spare time. Thus, I understand that he might want to try new technologies and frameworks to make the process more exciting for him, as learning new things is fun.

Overall, the frontend is relatively simple, so if he thinks that rewriting it is worth, I'm ok with it.

> @hacdias
> Why rewrite the front end? Again, lot of code that ... Well... Doesn't need to be there. A lot of old dependencies and updating them will be an hassle. The ideia is to revamp it and then install greenkeeper to maintain the dependencies up to date.

However, I think that we need to make the change clean. Should we keep the vue frontend in a new branch in filebrowser/frontend? Or, should be rename filebrowser/frontend to filebrowser/vue and create a new filebrowser/react?

In the end, we split the frontend precisely in other to allow multiple implementations.

---

About the DB, is it possible to implement a kind of plugin system so that it is easy to add interfaces to different DBs? A type that satisfies certain conditions, as a generic API. That would allow to use BoltDB, SQLite or any other without modifying the code base.

Anyway, as @Equim-chan commented:

> BoltDB is fine. It's not active because it's stable enough for now.

Also,

> @hacdias
> I saw there's a fork with some fixes and such and even they recommend us to use it.

This https://github.com/etcd-io/bbolt ?

---

> @vitality-kuzmich
> Does it costs to do so much effort into DB management(example mysql workbench) from console ? Are there workbenches for bolt DB ? Maybe replace with SQLlite and use some UI ? Here it is for bolt: evnix/boltdbweb but I did not test it...

Some months ago I searched for GUI and/or CLI tools to explore/edit BoltDB files, but I didn't find any. I guess it is because such tools need to be too specific for the data types that are been saved. Fortunately, @hacdias has now implemented it:

> I've already implemented all the needed CLI commands.

---

> @hacdias
> - Add an interactive first run experience through the command line to configure the stuff on the database and get rid of almost all flags.
>   - This would still let users create instances through scripts, they would just need to provide the stuff in the same order as it is asked.
>   - Also add commands to interact with the DB programatically.

> @hacdias
> If they use the commands from File Browser itself, they'll always make sure they have the correct DB structure. And lots of users have requested it already.

About getting rid of CLI flags, the JSON configuration file and environment variables to replace all of them with subcommands, I don't think it is a good idea. I definitely want to see some subcommands that allow to initialize the DB. That's cool and very useful. But I think that a configuration file should also be supported.

This is because it is easier to deploy a file (say JSON) that deploying a script that must be executed. On the one hand, a third-party service might allow users to create filebrowser instances by providing the config file only, without letting them execute arbitrary code. On the other hand, writing an interactive process and suggesting to *fake the interactivity* with a script is not a clean solution.

Please, let me know if I misunderstood anything.

---

> @hacdias
> Also, make filebrowser mainly a binary and move main.go to the root of the repo.
> That would also block FileBrowser from being used as a middleware.

I think it is useful to explicitly separate the core (`lib`) from CLI sources, as the core can be imported from third party projects, even though they don't use the CLI entrypoints.

Why do we need to break this setup? Did you have any compilation problem with the previous structure?

---

> Use github.com/spf13/afero as a FS layer instead of our own.

Sure.

---

> @helloray
> Folder upload(I can help to contribute it)

That's cool!

---

> @helloray
> Scrollbar management(The scrollbar position should be recorded and restored when user go back to parent directory. After user change a file name, the scrollbar should also jump to that file related area. )

I think that this should be extended to provide a mechanism to save user data in the browser: [Client-Side Storage](https://vuejs.org/v2/cookbook/client-side-storage.html). E.g., we might want to remember what type of view did the user select (maybe for each directory/folder).

---

> and please replace the editor, monaco(?) or ACE definitely. Thanks!

I am really interested in this. Do you have any reference to evaluate the alternatives? I suppose that better features have some impact on performance, so we should consider mobile devices before changing to a full-featured solution.

---

> @vitality-kuzmich
> Just thinking to implement file sharing, and put it as separate menu item, next to files listing.

I think this is a frontend design related enhancement. Therefore it has less priority that structural modifications, but it is still interesting to have it in mind. @hacdias, how can be track this? Should @vitality-kuzmich open a new issue and you can include it in the rewrite if it suits you?

---

About Caddy, I don't really know which are the implications of removing the integration. I have never used it. I have just tinkered with the build procedure.

**Comment by hacdias** [comment]
> I agree with:
> 
> > @helloray
> > At the moment, the most important thing is to introduce vendor management for go. Without that, the project can not be compiled if any go lib changing their APIs. Other contributors can gain benefits from it too.
> 
> The most important and urgent issue is to add go mod support to either v1.10.0 or to the current master branch. That will allow users to use the _old_ Filebrowser in a stable state. To do this, we need to decide:
> 
> * Stabilize v1.10.0 as v1.10.1 and jump directly to v2.0.0 in february.
> * Stabilize the current master branch as v2.0.0 and jump to v3.0.0 in february.
> * Stabilize the current master branch as v1.11.0 (although it might not be fully semver compilant) and jump to v2.0.0 in february.

Okay, so let's introduce go.mod on master and release minor version then.

> About rewriting the frontend with React, I quite agree with:
> 
> > @helloray
> > I don't know how much difference between VUE and React. If VUE works well, why spending so much time to rewrite it? Those frontend frameworks are almost changing everyday. The most popular framework can be die at any time. I suggest you keep working on features and bug fix. Do not rewrite it.
> 
> At the same time, @hacdias is young and this is a project he is doing in his spare time. Thus, I understand that he might want to try new technologies and frameworks to make the process more exciting for him, as learning new things is fun.
> 
> Overall, the frontend is relatively simple, so if he thinks that rewriting it is worth, I'm ok with it.

👍 

> However, I think that we need to make the change clean. Should we keep the vue frontend in a new branch in filebrowser/frontend? Or, should be rename filebrowser/frontend to filebrowser/vue and create a new filebrowser/react?

Yes, I'm working on the new one and I can create a new repo for it and leave the current where it is. When we move to v2.0 we can then rename the old to 'vue' and mark it as an archived repo.

> About getting rid of CLI flags, the JSON configuration file and environment variables to replace all of them with subcommands, I don't think it is a good idea. I definitely want to see some subcommands that allow to initialize the DB. That's cool and very useful. But I think that a configuration file should also be supported.
> 
> This is because it is easier to deploy a file (say JSON) that deploying a script that must be executed. On the one hand, a third-party service might allow users to create filebrowser instances by providing the config file only, without letting them execute arbitrary code. On the other hand, writing an interactive process and suggesting to _fake the interactivity_ with a script is not a clean solution.
> 
> Please, let me know if I misunderstood anything.

I should've updated this!! I've been working on [this branch](https://github.com/filebrowser/filebrowser/tree/rewrite). With that setup it will be impossible just to run `filebrowser` and expect it to work.

You'll always need to execute `fb config init` on the first time to generate the database and then `fb users new` to add the first user. They all use flags, none is interactive. Sorry for not updating this. Please try to run just to see the available commands.

We can add support to load the config from a file instead of just flags, but keep in mind that what's on the DB is what counts in the end. It's a way to centralize the config. We had it too split.

`fb` command will only take 4 flags: address, port, log and db path.

> I think it is useful to explicitly separate the core (`lib`) from CLI sources, as the core can be imported from third party projects, even though they don't use the CLI entrypoints.
> 
> Why do we need to break this setup? Did you have any compilation problem with the previous structure?
>
> About Caddy, I don't really know which are the implications of removing the integration. I have never used it. I have just tinkered with the build procedure.

I can answer both of this questions in one answer. For the first part, take a look at the structure of the branch I mentioned before. The things are exported and everyone is free to use them. They just need to have a database initialized, ready and working.

The plugin for Caddy has always created some constrains. We actually have lots of downloads on the Caddy page but not anymore since the build is broken...

Caddy can be used with v2.0 File Browser as a proxy, it just won't be only one binary. I can make a guide on how to use it.

---

Please take a look at the branch I'm working on: I'm doing first the Go part and then move to the frontend. The GO part is almost done. Really, almost. The codebase is not that big and I made some useful improvements.

**Comment by laoshaw** [comment]
I did some google check between Monaco editor and ACE, based on the posts I read the consensus is that, Monaco is a better one:

- https://github.com/Microsoft/monaco-editor/issues/19
- https://blog.expo.io/building-a-code-editor-with-monaco-f84b3a06deaf
- https://microsoft.github.io/monaco-editor/
- https://ace.c9.io/

As far as Vue vs React goes,they're still competing fiercely, isolate frontend as mentioned above will be nice.

**Comment by hacdias** [comment]
@1138-4EB @laoshaw I think it would be better to keep using Code Mirror. Monaco doesn't work on mobile and they don't even have plans to do so.

Code Mirror, right now, supports mobile and they're working on a [new version](https://codemirror.net/6/) and they're sponsored by some major companies. It will keep supporting mobile too so I think it's the best bet right now.

**Comment by hacdias** [comment]
Although I'll try adding monaco in and see how it works on my phone to see if it's that bad. I don't believe many people will be writing huge files on their phones.

Will also try ace

**Comment by hacdias** [comment]
We're sticking with **Ace** right now!

**Comment by zaichou** [comment]
> 1. Folder upload(I can help to contribute it)

i need it, thank you.

**Comment by hacdias** [comment]
@1138-4EB ready to release 2.0? 😄

**Comment by eine** [comment]
We should maybe consider releasing `2.0.0-rc.1` and asking for users to try it and report back?

**Comment by hacdias** [comment]
Actually I thought about that yesterday! We can do that, yes! I'm just updating some commands description. Can I ping you after I finish so you can roll that release? 😄

**Comment by hacdias** [comment]
@1138-4EB let's release it!

I've also removed branch v1. If we need it, we can just run `git checkout -b v1 v1.11.0`.

**Comment by eine** [comment]
It has been harder than expected, but [`v2.0.0-rc.1` is out](https://github.com/filebrowser/filebrowser/releases/tag/v2.0.0-rc.1)!

**Comment by helloray** [comment]
@hacdias @1138-4EB It seems search function is not working. Items in search results can not be opened by click. Another question: How to enable the builtin https? I tried the -t option,  but filebrowser was still using http not https.

**Comment by princemaple** [comment]
Does it integrate with caddy yet?

**Comment by hacdias** [comment]
@princemaple Caddy plugin will be available upon the next release of Caddy which can take a while yet. 

@helloray you must set both the certificate and the key for HTTPS to work. 

About search: it was working on my end two days ago and I don't remember changing anything about it. Hmm... I'll take a look just to make sure

**Comment by hacdias** [comment]
@helloray just tested and items seem to open on click. You can click and there is an error or you can't even click?

Although I found some other issues (not related to clickability): #625

**Comment by princemaple** [comment]
I build caddy from source. I should have asked "does it compile with caddy" rather. I just tried, it compiles.

```
/srv # caddy -plugins 
Server types: 
  http

Caddyfile loaders:
  short
  flag
  default

Other plugins:
  http.basicauth
  http.bind
  http.browse
  http.cache
  http.cors
  http.errors
  http.expvar
  http.ext
  http.fastcgi
  http.filebrowser  # <--
  http.gzip
  http.header
  http.index
  http.internal
  http.limits
  http.log
  http.markdown
  http.mime
  http.pprof
  http.proxy
  http.push
  http.redir
  http.request_id
  http.rewrite
  http.root
  http.status
  http.templates
  http.timeouts
  http.websocket
  on
  tls
  tls.storage.file
```
However I can't get filemanager/filebrowser to work.

When I used `filemanager`, I got:

    2019/01/09 10:41:53 no action found for directive 'filemanager' with server type 'http' (missing a plugin?)

`filebrowser` I got:

    2019/01/09 10:41:37 /etc/Caddyfile:3 - Error during parsing: Unknown directive 'filebrowser'

So I assume there is more work to be done and I will have to wait a little bit?

**Comment by princemaple** [comment]
Oh I see, I am currently building against caddy v0.11.1 which hasn't got [this commit](https://github.com/mholt/caddy/commit/f5aaa471deb35fad58a5a6394b05bbf7e42ac61a) yet.

**Comment by hacdias** [comment]
@princemaple the caddy plugin is not yet finished. It will be finished at most next week. If you look at the repo (filebrowser/caddy) you'll see a lot of code commented and unfinished.

**Comment by princemaple** [comment]
Ah thanks for the information

**Comment by hacdias** [comment]
~@1138-4EB I think we should release v2.0.0 now. Any bugs or fixes can go in the next patch releases.~

Releasing v2.0.0-rc.2 now.

**Comment by nambrosch** [comment]
thank you for all of the hard work, there is such a mixed bag of products in this space right now.  i was wondering if object previews (image thumbnails) or binding to an external ldap server is in filebrowser's future?

**Comment by eine** [comment]
@nambrosch see https://github.com/filebrowser/filebrowser/issues/489#issuecomment-452224608 and #128.

**Comment by hacdias** [comment]
Closing this as officially released 😄
